name: TalkNetSpect
sample_rate: 22050

train_dataset: ???
validation_datasets: ???
durs_file: ???
f0_file: ???

model:
  d_char: 128
  n_mels: 80
  dropout: 0.1
  separable: true

  train_ds:
    dataset:
      _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharWithDursF0Dataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.1
      int_values: false
      load_audio: true
      normalize: false
      sample_rate: ${sample_rate}
      trim: false
      durs_file: ${durs_file}
      f0_file: ${f0_file}
      blanking: true
      vocab:
        notation: phonemes
        punct: true
        spaces: true
        stresses: false
        add_blank_at: last
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 64
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharWithDursF0Dataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.1
      int_values: false
      load_audio: true
      normalize: false
      sample_rate: ${sample_rate}
      trim: false
      durs_file: ${durs_file}
      f0_file: ${f0_file}
      blanking: true
      vocab:
        notation: phonemes
        punct: true
        spaces: true
        stresses: false
        add_blank_at: last
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 64
      num_workers: 1

  preprocessor:
    _target_: "nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor"
    dither: 0.0
    features: ${model.n_mels}
    frame_splicing: 1
    highfreq: 8000
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: 1024
    n_window_size: 1024
    window_size: False
    n_window_stride: 256
    window_stride: False
    normalize: null
    pad_to: 1
    pad_value: -11.52
    preemph: null
    sample_rate: ${sample_rate}
    stft_conv: false
    window: hann

  model:
    _target_: "nemo.collections.asr.modules.ConvASREncoder"
    feat_in: ${model.d_char}
    activation: relu
    conv_mask: true

    jasper:
    - filters: 256
      repeat: 3
      kernel: [3]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}

    - filters: 256
      repeat: 5
      kernel: [5]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 256
      repeat: 5
      kernel: [7]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 256
      repeat: 5
      kernel: [9]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 256
      repeat: 5
      kernel: [13]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 256
      repeat: 5
      kernel: [15]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 256
      repeat: 5
      kernel: [17]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 512
      repeat: 5
      kernel: [21]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 512
      repeat: 5
      kernel: [23]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 512
      repeat: 5
      kernel: [25]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true
      separable: ${model.separable}
      se: true
      se_reduction_ratio: 8

    - filters: 1024
      repeat: 1
      kernel: [1]
      stride: [1]
      dilation: [1]
      dropout: ${model.dropout}
      residual: true

  optim:
    name: adam
    lr: 1e-3
    weight_decay: 1e-6

    sched:
      name: CosineAnnealing
      min_lr: 1e-5
      warmup_ratio: 0.02

trainer:
  gpus: 1
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False
  logger: False
  gradient_clip_val: 1.0
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 200
  check_val_every_n_epoch: 25

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: "val_loss"
    mode: "min"
